### ISSUE TITLE
Command line version misses plate query

### ISSUE THREAD

**Issue by MartinFXP** [cbg-ethz/rnaiutilities#15]

**Comment by dirmeier** [comment]
So this is not supported so far:
 
```
rnai-query query --plate OUTFILE
```

**Comment by dirmeier** [comment]
This https://github.com/cbg-ethz/rnaiutilities/commit/ea6d31e9e63243a53440a237c7625aa086a164ed  and this  [v0.1.1.post1](https://github.com/cbg-ethz/rnaiutilities/releases/tag/v0.1.1.post1) fix it. If it's fine, can you close this please?
