### ISSUE TITLE
getting a subset of information for a specific subset of variables

### ISSUE THREAD

**Issue by MartinFXP** [cbg-ethz/rnaiutilities#21]
At the moment I can get the list of genes which have been perturbed via

```
rnai-query select gene
```

If possible, I'd like to get a subset of genes for a specific list of set variables. E.g. all genes which have been perturbed for the shigella pathogen with pooled siRNAs within the infectx study:

```
 rnai-query select gene —pathogen shigella —design p —study infectx
```

This of course not only for the `gene` variable but for others, too. E.g. for which pathogens do we have pooled siRNA perturbations?

```
rnai-query select pathogen --design p
```

**Comment by dirmeier** [comment]
That sounds like a reasonable feature....I do it asap.

**Comment by dirmeier** [comment]
Hey, this [`release`](https://github.com/cbg-ethz/rnaiutilities/releases/tag/v0.1.3) allows filtering.

**However, in some cases there is unexpected behaviour, so you have to be aware what is really happening.**

For example, for

```bash
  rnai-query select --db test_case.db --gene mock --plate dz05-1e sirna
```

I guess you would want to filter on plate `dz05-1e` and gene `mock` and for these two conditions get all the sirna IDs. However, the query we are building looks like that:

```sql
 SELECT distinct sirna
	FROM (SELECT * FROM meta WHERE (plate='dz05-1e')) a1
	JOIN (SELECT *
		FROM (SELECT * FROM gene WHERE (gene='mock')) a1
		JOIN (SELECT * FROM sirna) a2
		ON (a1.filename = a2.filename)
	) a2
	ON (a1.filename = a2.filename);
```
which is read from the inside to the outside. I'll quickly explain what is happening:

```sql
(SELECT * FROM sirna) a2
```
translates to: give me all info (`*`) from the `sirna` table and save it in a variable `a2`.

```sql
(SELECT * FROM gene WHERE (gene='mock')) a1
```
translates to: give me all info (`*`) from the `gene`  table where the gene must be `mock` and save it in a variable `a1`.

```sql
(SELECT * FROM (...) a1
		 JOIN (...) a2
		 ON (a1.filename = a2.filename)) a2
```
translates to: `join` these two tables on the attribute `filename` and discard everything that is not matching (that is the default from `join`).
Then save ave the result of this join in a variable `a2`, where we again select all (`*`) columns from the joined table.

```sql
SELECT distinct sirna
    FROM (SELECT * FROM meta WHERE (plate='dz05-1e')) a1
        JOIN ( ... see before ... ) a2
	ON (a1.filename = a2.filename);
```
Here we take all (`*`) the information from the `meta` where the plate is `dz05-1e`, save the result in a variable `a1` and do a `join` on our previous result, which we called `a2`. We join on the filenames again. Finally we select unique `sirna` ids.

So, what is happening here is, that we dont make use of the sirna information, but filter on the filenames, which leads to too many results (i.e. all results that fit the filenames). So you would'nt get the sirnas that are filtered by the gene mock, but all sirnas on the plate where the filenames were joined. 

The only way out from this, is to add the gene-sirnas matchings in another table, which we should probably aim for. The reason why we haven't done this before is, cause we did the filtering in memory for `rnai-query query` and didn't need the filtering on the `DB` side. So we got filenames from the DB, iterate over them and filter/sample cells by gene/sirna.

This is the only use-case I could think of that has unintended behaviour (i.e., filtering + selecting on genes/sirnas). These work fine, I think:

```bash
   # note that order of the arguments:
   # subcommand (select) -> filters -> selector
   rnai-query select --db tix.db --plate dz05-1e gene
   rnai-query select --db tix.db --gene pik3ca sirna
   rnai-query select --db tix.db --pathogen shigella --design p --study infectx gene
```

One more thing: the `join`s of `gene` and `sirna` tables are rather slow at the moment (cause the tables are quite long and you do pairwise comparisons). I try to speed this up..
